<?php
/**
 * CFRefundRequest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * New Payment Gateway APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2022-01-01
 * Contact: nextgenapi@cashfree.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CFRefundRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class CFRefundRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CFRefundRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'refund_amount' => 'double',
        'refund_id' => 'string',
        'refund_note' => 'string',
        'refund_speed' => 'string',
        'refund_splits' => '\OpenAPI\Client\Model\CFVendorSplit[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'refund_amount' => 'double',
        'refund_id' => null,
        'refund_speed' => null,
        'refund_note' => null,
        'refund_splits' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'refund_amount' => 'refund_amount',
        'refund_id' => 'refund_id',
        'refund_note' => 'refund_note',
        'refund_splits' => 'refund_splits',
        'refund_speed' => 'refund_speed',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'refund_amount' => 'setRefundAmount',
        'refund_id' => 'setRefundId',
        'refund_note' => 'setRefundNote',
        'refund_splits' => 'setRefundSplits',
        'refund_speed' => 'setRefundSpeed'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'refund_amount' => 'getRefundAmount',
        'refund_id' => 'getRefundId',
        'refund_note' => 'getRefundNote',
        'refund_splits' => 'getRefundSplits',
        'refund_speed' => 'getRefundSpeed'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['refund_amount'] = $data['refund_amount'] ?? null;
        $this->container['refund_id'] = $data['refund_id'] ?? null;
        $this->container['refund_note'] = $data['refund_note'] ?? null;
        $this->container['refund_splits'] = $data['refund_splits'] ?? null;
        $this->container['refund_speed'] = $data['refund_speed'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['refund_amount'] === null) {
            $invalidProperties[] = "'refund_amount' can't be null";
        }
        if ($this->container['refund_id'] === null) {
            $invalidProperties[] = "'refund_id' can't be null";
        }
        if ((mb_strlen($this->container['refund_id']) > 40)) {
            $invalidProperties[] = "invalid value for 'refund_id', the character length must be smaller than or equal to 40.";
        }

        if ((mb_strlen($this->container['refund_id']) < 3)) {
            $invalidProperties[] = "invalid value for 'refund_id', the character length must be bigger than or equal to 3.";
        }

        if (!is_null($this->container['refund_note']) && (mb_strlen($this->container['refund_note']) > 100)) {
            $invalidProperties[] = "invalid value for 'refund_note', the character length must be smaller than or equal to 100.";
        }

        if (!is_null($this->container['refund_note']) && (mb_strlen($this->container['refund_note']) < 3)) {
            $invalidProperties[] = "invalid value for 'refund_note', the character length must be bigger than or equal to 3.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets refund_amount
     *
     * @return double
     */
    public function getRefundAmount()
    {
        return $this->container['refund_amount'];
    }

    /**
     * Sets refund_amount
     *
     * @param double $refund_amount Amount to be refunded. Should be lesser than or equal to the transaction amount. (Decimals allowed)
     *
     * @return self
     */
    public function setRefundAmount($refund_amount)
    {
        $this->container['refund_amount'] = $refund_amount;

        return $this;
    }

    /**
     * Gets refund_speed
     *
     * @return double
     */
    public function getRefundSpeed()
    {
        return $this->container['refund_speed'];
    }

    /**
     * Sets refund_speed
     *
     * @param double $refund_speed
     *
     * @return self
     */
    public function setRefundSpeed($refund_speed)
    {
        $this->container['refund_speed'] = $refund_speed;

        return $this;
    }

    /**
     * Gets refund_id
     *
     * @return string
     */
    public function getRefundId()
    {
        return $this->container['refund_id'];
    }

    /**
     * Sets refund_id
     *
     * @param string $refund_id An unique ID to associate the refund with. Provie alphanumeric values
     *
     * @return self
     */
    public function setRefundId($refund_id)
    {
        if ((mb_strlen($refund_id) > 40)) {
            throw new \InvalidArgumentException('invalid length for $refund_id when calling CFRefundRequest., must be smaller than or equal to 40.');
        }
        if ((mb_strlen($refund_id) < 3)) {
            throw new \InvalidArgumentException('invalid length for $refund_id when calling CFRefundRequest., must be bigger than or equal to 3.');
        }

        $this->container['refund_id'] = $refund_id;

        return $this;
    }

    /**
     * Gets refund_note
     *
     * @return string|null
     */
    public function getRefundNote()
    {
        return $this->container['refund_note'];
    }

    /**
     * Sets refund_note
     *
     * @param string|null $refund_note A refund note for your reference.
     *
     * @return self
     */
    public function setRefundNote($refund_note)
    {
        if (!is_null($refund_note) && (mb_strlen($refund_note) > 100)) {
            throw new \InvalidArgumentException('invalid length for $refund_note when calling CFRefundRequest., must be smaller than or equal to 100.');
        }
        if (!is_null($refund_note) && (mb_strlen($refund_note) < 3)) {
            throw new \InvalidArgumentException('invalid length for $refund_note when calling CFRefundRequest., must be bigger than or equal to 3.');
        }

        $this->container['refund_note'] = $refund_note;

        return $this;
    }

    /**
     * Gets refund_splits
     *
     * @return \OpenAPI\Client\Model\CFVendorSplit[]|null
     */
    public function getRefundSplits()
    {
        return $this->container['refund_splits'];
    }

    /**
     * Sets refund_splits
     *
     * @param \OpenAPI\Client\Model\CFVendorSplit[]|null $refund_splits refund_splits
     *
     * @return self
     */
    public function setRefundSplits($refund_splits)
    {
        $this->container['refund_splits'] = $refund_splits;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


